#!/bin/bash

set -e
rm function.zip || true
cd v-env/lib/python3.7/site-packages/
zip -r9 ../../../../function.zip .
cd ../../../../
zip -R function.zip "*.py" -x v-env/\*
aws lambda update-function-code --function-name items --zip-file fileb://function.zip