#!/bin/bash

set -e

# replace password placeholder with real aws password from stdin
awk '{sub(/_password_/,'\"$2\"')}1' rds_config.py > temp.py && mv temp.py rds_config.py

# zipping
rm function.zip || true
cd .venv/lib/python3.7/site-packages/
zip -r9 ../../../../function.zip .
cd ../../../../
zip -g function.zip rds_config.py
zip -R function.zip "$1_service/*.py"
zip -R function.zip utils.py

# update aws lambda
aws lambda update-function-code --function-name $1 --zip-file fileb://function.zip

# reset password to placeholder
awk '{sub(/'$2'/,"_password_")}1' rds_config.py > temp.py && mv temp.py rds_config.py
