#!/bin/bash

set -e

# copy dev config
cat config/function_config_dev.py > config/function_config.py

# zipping
rm function.zip || true
cd .venv/lib/python3.8/site-packages/
zip -r9 ../../../../function.zip .
cd ../../../../
zip -R function.zip "$1_service/*.py"
zip -R function.zip utils.py
zip -R function.zip config/function_config.py

# update aws lambda
aws lambda update-function-code --function-name "$1-dev" --zip-file fileb://function.zip

# clear config
> config/function_config.py