#!/bin/bash

set -e

# zipping
rm function.zip || true
zip -R function.zip "email_service/*.py"

# update aws lambda
aws lambda update-function-code --function-name EmailPublisher --zip-file fileb://function.zip
